name: Build imm-25.12 for jp-tvbox

on:
  workflow_dispatch:
   inputs:
      ssh:
        description: 'SSH connection to Actions'
        required: true
        default: 'false'
        type: choice
        options:
          - true
          - false

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  REPO_URL: https://github.com/immortalwrt/immortalwrt
  REPO_BRANCH: openwrt-25.12
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
    - name: Checkout
      uses: actions/checkout@main

    - name: Initialize environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E apt-get -qq update > /dev/null
        sudo -E apt-get -qq install -y $(curl -fsSL https://raw.githubusercontent.com/nantayo/My-Pkg/master/openwrt) > /dev/null
        sudo -E apt-get -qq autoremove --purge > /dev/null
        sudo -E apt-get -qq clean > /dev/null
        sudo timedatectl set-timezone "$TZ"
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir

    - name: Clone source code
      working-directory: /workdir
      run: |
        git clone $REPO_URL -b $REPO_BRANCH --single-branch --depth=1 openwrt
        ln -sf /workdir/openwrt $GITHUB_WORKSPACE/openwrt
        echo "FILE_DATE=$(date +"%Y%m%d")" >> $GITHUB_ENV

    - name: Update & Install feeds
      run: |
        chmod +x JP-TVbox/diy.sh
        cd openwrt
        ./scripts/feeds update -a
        $GITHUB_WORKSPACE/JP-TVbox/diy.sh
        ./scripts/feeds update -a
        ./scripts/feeds install -a

    - name: Load custom config
      run: |
        rm -rf openwrt/files openwrt/.config
        mv JP-TVbox/files JP-TVbox/.config openwrt/

    - name: Download package
      working-directory: ./openwrt
      run: |
        make defconfig
        make download -j$(( $(nproc) * 2 ))
        find dl -size -1k -exec rm -f {} \;

    - name: Compile the firmware
      run: |
        chmod -R 755 openwrt
        cd openwrt
        echo -e "$(nproc) thread compile"
        make -j$(( $(nproc) + 1 )) || make -j1 V=s

    - name: Package armsr as openwrt
      uses: ophub/amlogic-s9xxx-openwrt@main
      with:
        openwrt_path: openwrt/bin/targets/armsr/armv8/*rootfs.tar.gz
        openwrt_board: rk3566
        kernel_repo: ophub/kernel
        kernel_usage: ophub
        openwrt_kernel: 6.18.38
        builder_name: Jumbotsang

    - name: Upload firmware to release
      uses: softprops/action-gh-release@master
      with:
        tag_name: OpenWrt_${{ env.FILE_DATE }}
        files: ${{ env.PACKAGED_OUTPUTPATH }}/*.img.gz
        body: |
          首次使用建议全新刷写
          * 基本信息
          IP: 192.168.50.2
          账户: root
          密码: password

    - name: Delete old releases
      uses: mgz0227/delete-older-releases@master
      with:
        keep_latest: 3
        delete_tags : true
